# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mKGQNtiOcA5fa_O9SxE1ECcLpUfdri5X
"""

amount = 1000 # initial amount with trader
portfolio = 0 # this denotes the current number of shares with trader
money_end = amount # this is the amount left after trading, initial value is equal to amount
investment = [] # this list keeps track of investments with the last value in list giving the total investment till time
transaction_cost = 0.0075 # a trasaction cost charged for trading

def buy(quantity, price):
  global portfolio, money_end
  allocated_money = quantity*price
  money_end = money_end - allocated_money - transaction_cost * allocated_money
  portfolio += quantity
  if investment == []:
    investment.append(allocated_money)
  else:
    investment.append(allocated_money)
    investment[-1] += investment[-2]

def sell(quantity, price):
  global portfolio, money_end
  allocated_money = quantity*price
  money_end = money_end + allocated_money - transaction_cost * allocated_money
  portfolio -= quantity
  investment.append(-allocated_money)
  investment[-1] += investment[-2]